# Generated by Django 3.1.1 on 2020-09-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth',
            field=models.CharField(default='username', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(default='email', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='username', max_length=64),
        ),
    ]
